version: '3.7'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn store_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:11
    volumes: 
        - postgres_data:/var/lib/postgresql/data/

volumes: 
    postgres_data:
